// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OBDInsightBot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260216100049_MigrationBlogpostitem")]
    partial class MigrationBlogpostitem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("OBDInsightBot.Models.BlogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionInBlog")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("WrittenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("contence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cssCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.ToTable("BlogItems");
                });

            modelBuilder.Entity("OBDInsightBot.Models.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MiniDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathForFeaturedImage")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("WrittenAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("OBDInsightBot.Models.UserChatItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatContent")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChatPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserSessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserSessionId")
                        .HasDatabaseName("IX_UserChatItems_SessionId");

                    b.HasIndex("UserSessionId", "ChatPosition")
                        .HasDatabaseName("IX_UserChatItems_SessionId_Position");

                    b.ToTable("UserChatItems");
                });

            modelBuilder.Entity("OBDInsightBot.Models.UserOBDData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AirIntakeTemp")
                        .HasColumnType("TEXT");

                    b.Property<string>("AmbientAirTemp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Automatic")
                        .HasColumnType("TEXT");

                    b.Property<string>("BarometricPressureKpa")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("DaysOfWeek")
                        .HasColumnType("TEXT");

                    b.Property<string>("DtcNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineCoolantTemp")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineLoad")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnginePower")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineRpm")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineRuntime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquivRatio")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelPressure")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hours")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntakeManifoldPressure")
                        .HasColumnType("TEXT");

                    b.Property<string>("LongTermFuelTrimBank2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Maf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mark")
                        .HasColumnType("TEXT");

                    b.Property<string>("Min")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Months")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortTermFuelTrimBank1")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortTermFuelTrimBank2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Speed")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThrottlePos")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimingAdvance")
                        .HasColumnType("TEXT");

                    b.Property<string>("TroubleCodes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserSessionId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserOBDData_SessionId");

                    b.ToTable("UserOBDDatas");
                });

            modelBuilder.Entity("OBDInsightBot.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SessionStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedDataPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("lastUseTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("lastUseTime")
                        .HasDatabaseName("IX_UserSessions_LastUseTime");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("OBDInsightBot.Models.BlogItem", b =>
                {
                    b.HasOne("OBDInsightBot.Models.BlogPost", "BlogPost")
                        .WithMany()
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("OBDInsightBot.Models.UserChatItem", b =>
                {
                    b.HasOne("OBDInsightBot.Models.UserSession", "UserSession")
                        .WithMany()
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("OBDInsightBot.Models.UserOBDData", b =>
                {
                    b.HasOne("OBDInsightBot.Models.UserSession", "UserSession")
                        .WithMany()
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSession");
                });
#pragma warning restore 612, 618
        }
    }
}
